# Generated by Django 4.0.5 on 2024-02-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_buyer_pic_alter_product_pic1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
